version: '3'

volumes:
  vbb_local_postgres_data: {}
  vbb_local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: vbb_production_postgres
    container_name: vbb_local_postgres
    volumes:
      - vbb_local_postgres_data:/var/lib/postgresql/data:Z
      - vbb_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
        - "5432:5432"
    expose:
        - "5432"
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vbb_local_django
    container_name: vbb_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  docs:
    image: vbb_local_docs
    container_name: vbb_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./vbb:/app/vbb:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: vbb_local_redis

  celeryworker:
    <<: *django
    image: vbb_local_celeryworker
    container_name: vbb_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: vbb_local_celerybeat
    container_name: vbb_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: vbb_local_flower
    container_name: vbb_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
