version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: vbb_production_django
    deploy:
      resources:
        limits:
          memory: 2G
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: vbb_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    ports:
        - "5432:5432"
    expose:
        - "5432"
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: vbb_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: vbb_production_celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: vbb_production_celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: vbb_production_flower
    ports: []
    command: /start-flower
