# Generated by Django 4.0.3 on 2022-04-15 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0001_initial'),
        ('language', '0001_initial'),
        ('careers', '0001_initial'),
        ('profiles', '0003_mentorprofile_is_of_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('assigned_library', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libraries.library')),
                ('careers_of_interest', models.ManyToManyField(related_name='+', to='careers.career')),
                ('mentoring_languages', models.ManyToManyField(related_name='+', to='language.language')),
                ('subjects', models.ManyToManyField(related_name='+', to='subjects.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
