# Generated by Django 3.2.13 on 2022-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_studentprofile_assigned_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarianprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
