# Generated by Django 3.2.13 on 2022-06-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220608_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='family_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Family Status'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='family_support_level',
            field=models.IntegerField(choices=[(1, 'Very supportive'), (2, 'Supportive'), (3, 'Less supportive'), (4, 'Not supportive at all')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.IntegerField(choices=[(1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade'), (9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_obstacle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Government Obstacle'),
        ),
    ]
