# Generated by Django 3.2.13 on 2022-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_genre'),
        ('profiles', '0009_auto_20220627_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='favorite_genres',
            field=models.ManyToManyField(related_name='_profiles_studentprofile_favorite_genres_+', to='subjects.Genre'),
        ),
    ]
