# Generated by Django 3.2.13 on 2022-06-27 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_studentprofile_favorite_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Opportunity',
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='how_found_us',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
