# Generated by Django 3.2.13 on 2022-06-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220627_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='how_found_us',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
