# Generated by Django 3.2.13 on 2022-07-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_auto_20220707_2234'),
        ('profiles', '0013_auto_20220629_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='assigned_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.library'),
        ),
    ]
