# Generated by Django 3.2.13 on 2022-07-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_advisorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Reviewed', 'Not Reviewed'), ('Rejected', 'Rejected')], default='Not Reviewed', max_length=50),
        ),
    ]
