# Generated by Django 3.2.13 on 2022-07-26 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_studentprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='canMeetConsistently',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='crimesOrMisdemeanor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='crimesOrMisdemeanorResponses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='meet_provider',
            field=models.IntegerField(choices=[(0, 'google'), (1, 'microsoft'), (2, 'zoom'), (3, 'other'), (4, 'none')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='opportunities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.opportunity'),
        ),
    ]
