# Generated by Django 3.2.13 on 2022-06-08 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
