# Generated by Django 4.0.3 on 2022-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_display_name', models.CharField(max_length=255, unique=True)),
                ('name_in_native_alphabet', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
