# Generated by Django 4.0.3 on 2022-05-20 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_library_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='announcements',
        ),
    ]
