# Generated by Django 3.2.13 on 2022-06-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_library_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerreservation',
            name='computer',
        ),
        migrations.AddField(
            model_name='userpreferenceslot',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.computer'),
        ),
        migrations.AlterField(
            model_name='computerreservation',
            name='reserved_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.userpreferenceslot'),
        ),
    ]
