# Generated by Django 3.2.13 on 2022-07-01 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20220630_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferenceslot',
            name='computer',
        ),
        migrations.AddField(
            model_name='computerreservation',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.computer'),
        ),
    ]
