# Generated by Django 3.2.13 on 2022-07-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_auto_20220707_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_down',
            field=models.BooleanField(default=False),
        ),
    ]
