# Generated by Django 3.2.13 on 2022-07-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_computer_is_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
