# Generated by Django 3.2.13 on 2022-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_alter_announcement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferenceslot',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
