# Generated by Django 3.2.13 on 2022-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_alter_userpreferenceslot_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerreservation',
            name='mentor_attended_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='computerreservation',
            name='student_attended_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
