# Generated by Django 3.2.13 on 2022-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_alter_userpreferenceslot_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferenceslot',
            name='conference_type',
            field=models.CharField(blank=True, default='google', max_length=1024, null=True),
        ),
    ]
