# Generated by Django 3.2.12 on 2022-02-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_display_name', models.CharField(max_length=255, unique=True)),
                ('name_in_naitve_alphabet', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(max_length=255, unique=True)),
                ('is_corporate_org', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.CharField(max_length=255)),
                ('is_accepting_new_mentors', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('advisors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_video_url', models.TextField(null=True)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Not Reviewed', 'Not Reviewed'), ('Rejected', 'Rejected')], default='Not Reviewed', max_length=30)),
                ('has_viewed_donation_page', models.BooleanField(default=False)),
                ('has_completed_training', models.BooleanField(default=False)),
                ('has_clicked_facebook_workplace_invite', models.BooleanField(default=False)),
                ('interests', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('secondary_email', models.CharField(max_length=255, null=True)),
                ('assigned_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.program')),
                ('careers', models.ManyToManyField(related_name='_users_mentorprofile_careers_+', to='users.Career')),
                ('languages', models.ManyToManyField(related_name='_users_mentorprofile_languages_+', to='users.Language')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('subjects', models.ManyToManyField(related_name='_users_mentorprofile_subjects_+', to='users.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
