# Generated by Django 3.2.13 on 2022-06-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220624_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Mentor'), (3, 'Advisor'), (4, 'Librarian'), (5, 'Admin')], default=0, null=True),
        ),
    ]
