# Generated by Django 4.0.3 on 2022-04-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(max_length=255, unique=True)),
                ('is_corporate_org', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('libary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libraries.library')),
            ],
        ),
    ]
