# Generated by Django 4.0.3 on 2022-04-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email_domain',
            new_name='corporate_code',
        ),
    ]
