# Generated by Django 4.0.3 on 2022-04-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='libary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.library'),
        ),
    ]
