# Generated by Django 4.0.3 on 2022-04-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_email_domain_organization_corporate_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='libary',
            new_name='library',
        ),
    ]
