# Generated by Django 4.0.3 on 2022-04-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('organizations', '0003_rename_libary_organization_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libraries.library'),
        ),
    ]
